version: "0.1.{build}"
image: Visual Studio 2019

branches:
  only:
    - master
    - release

init:
  - cmd: git config --global core.autocrlf true

install:
  - cmd: dotnet --version
  - cmd: dotnet tool restore

for:
  - branches:
      only:
        - master
    before_build:
      - cmd: dotnet fake build -t UpdateVersion-CI %APPVEYOR_BUILD_VERSION% preview

build_script:
  - cmd: dotnet fake build

test_script:
  - cmd: dotnet test PPBackup.Base.Tests\PPBackup.Base.Tests.csproj

artifacts:
  - path: build\artifacts\*

clone_depth: 1

deploy: off
