name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Check .NET Core version
        run: |
          dotnet --version

      - name: Build
        run: ./build win64

      - name: Test
        run: ./build test

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows x64 Installer
          path: output/taskington-setup-win64-*.exe

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Windows x64 Installer
      - name: Create draft release
        run: |
          gh release create "${GITHUB_REF#refs/tags/}" --draft --title "${GITHUB_REF#refs/tags/v}" *
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}