name: CI

on:
  push:
    branches:
      - master
      - ghaction
      - nukebuild
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Check .NET Core version
        run: |
          dotnet --version

      - name: Build
        run: ./build win64

      - name: Test
        run: ./build test

      - name: Archive artifacts
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/nukebuild'
        uses: actions/upload-artifact@v2
        with:
          name: Windows x64 Installer
          path: output/ppbackup-setup-win64-*.exe
